export const data = [
    {id: 0, name: "đồng hồ", customer: "Bảo Trân", amount: 2, price: 10000, status:false},
    {id: 1, name: "nhẫn bạc", customer: "Như Ngọc", amount: 1, price: 15000, status:true},
    {id: 2, name: "nhẫn vàng", customer: "Tâm Anh", amount: 1, price: 30000, status:false},
    {id: 3, name: "vòng tay", customer: "Bảo Trân", amount: 3, price: 76000, status:true},
    {id: 4, name: "khuyên tai", customer: "Đình Kha", amount: 0, price: 0, status:true},
    {id: 5, name: "đồng hồ", customer: "Bảo Trân", amount: 1, price: 0, status:true},
    {id: 6, name: "nhẫn bạc", customer: "Như Ngọc", amount: 0, price: 0, status:true},
    {id: 7, name: "nhẫn vàng", customer: "Tâm Anh", amount: 0, price: 0, status:true},
    {id: 8, name: "vòng tay", customer: "Bảo Trân", amount: 0, price: 0, status:true},
    {id: 9, name: "khuyên tai", customer: "Đình Kha", amount: 0, price: 0, status:true},
    {id: 10, name: "đồng hồ", customer: "Bảo Trân", amount: 1, price: 0, status:false},
    {id: 11, name: "nhẫn bạc", customer: "Như Ngọc", amount: 0, price: 0, status:true},
    {id: 12, name: "nhẫn vàng", customer: "Tâm Anh", amount: 0, price: 0, status:true},
    {id: 13, name: "vòng tay", customer: "Bảo Trân", amount: 0, price: 0, status:true},
    {id: 14, name: "khuyên tai", customer: "Đình Kha", amount: 0, price: 0, status:true},
    {id: 15, name: "đồng hồ", customer: "Bảo Trân", amount: 1, price: 0, status:false},
    {id: 16, name: "nhẫn bạc", customer: "Như Ngọc", amount: 0, price: 0, status:true},
    {id: 17, name: "nhẫn vàng", customer: "Tâm Anh", amount: 0, price: 0, status:true},
    {id: 18, name: "vòng tay", customer: "Bảo Trân", amount: 0, price: 0, status:true},
    {id: 19, name: "khuyên tai", customer: "Đình Kha", amount: 0, price: 0, status:false},
]
